# Generated by Django 5.2.13 on 2026-04-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_task_task_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tasks',
            new_name='task',
        ),
    ]
